packages/typescript-private/device-server/src/device-inspector/device-inspector.controller.ts
packages/typescript-private/device-server/src/gamium/gamium.context.ts
packages/typescript/device-client-common/src/specs/http/device-dtos.ts
packages/typescript/device-client-common/src/specs/http/device-inspector.ts
projects/console-web-front/src/components/streaming/GameObjectDetail.tsx
projects/console-web-front/src/components/streaming/InspectObjectProperty.tsx
projects/console-web-front/src/components/streaming/Inspector.tsx
projects/console-web-front/src/components/streaming/InspectorSelectedNode.tsx
projects/console-web-front/src/components/streaming/StreamingVideo.tsx
projects/console-web-front/src/hooks/streaming/useInspector.ts
projects/console-web-front/src/modules/inspector/gamium.ts
projects/console-web-front/src/modules/inspector/index.ts
projects/console-web-front/src/types/inspector.ts
projects/console-web-front/src/utils/browser-device-inspector.ts
projects/go-device-controller/internal/pkg/streamer/labeled_datachannel.go

Gamium inspector for web (#14)

Gamium inspector for web

---

nm-space/projects/dost/electron/child/child-service.ts
nm-space/projects/dost/electron/env.ts
nm-space/projects/dost/electron/feature-config/feature-config-service.ts
nm-space/projects/dost/electron/main.ts
nm-space/projects/dost/electron/preload.ts
nm-space/projects/dost/electron/updater/updater-service.ts
nm-space/projects/dost/features/development.feature.config.json
nm-space/projects/dost/features/e2e.feature.config.json
nm-space/projects/dost/features/local.feature.config.json
nm-space/projects/dost/features/production.feature.config.json
nm-space/projects/dost/features/self-hosted.feature.config.json
nm-space/projects/dost/src/App.tsx
nm-space/projects/dost/src/index.tsx
nm-space/projects/dost/src/pages/Connect.tsx
nm-space/projects/dost/src/pages/Settings.tsx
nm-space/projects/dost/src/pages/SetupManual.tsx
nm-space/projects/dost/src/pages/Splash.tsx
nm-space/projects/dost/src/shares/feature-config.ts
nm-space/projects/dost/src/stores/environment.ts
packages/typescript-dev-private/publish-package/src/common.ts
packages/typescript-dev-private/publish-package/src/git-repo/github-action-publisher.ts
packages/typescript-dev-private/publish-package/src/git-repo/gitlab-template-publisher.ts
packages/typescript-dev-private/publish-package/src/npm/publisher.ts
packages/typescript-private/host-agent/src/processor/action.processor.ts
packages/typescript/node/src/feature-config.ts

feat(dogu-agent-feature-control): add feature #22

---

packages/typescript-private/console/src/base/device.ts
packages/typescript/types/src/platforms.ts
projects/console-web-server/src/db/entity/device.entity.ts
projects/console-web-server/src/db/migrations/local/1689059705506-typeorm-migration.ts
projects/console-web-server/src/module/event/pipeline/device-job-updater.ts
projects/console-web-server/src/module/organization/device/device-status.service.ts
projects/console-web-server/src/module/organization/device/dto/device.dto.ts

update: deviceJob max parallel count

---

nm-space/projects/dost/src/pages/SetupManual.tsx

https://github.com/dogu-team/dogu/issues/126

fix: poop: skip manual setup

---

packages/typescript-private/device-server/src/internal/driver/ios-driver.ts
packages/typescript-private/device-server/src/internal/externals/cli/system-profiler.ts
packages/typescript-private/device-server/src/internal/externals/index.ts

- [v] Local, Self Hosted and Development environment test finished.
- [v] Local, E2E, Self Hosted, Development and Production env variable checked.
- [v] (Backend only) DB migration file creation checked.
- [v] **If this is a API deleted or changed**: Check side effects for API deletion or related code change.

fix: ios connection issue

---

packages/typescript-private/console/src/base/organization.ts
packages/typescript-private/console/src/dto/team/team.dto.ts
projects/console-web-server/src/db/entity/organization.entity.ts
projects/console-web-server/src/db/migrations/local/1689564497578-typeorm-migration.ts
projects/console-web-server/src/module/organization/dto/organization.dto.ts
projects/console-web-server/src/module/organization/organization.controller.ts
projects/console-web-server/src/module/organization/organization.service.ts

feat: organization tutorial api

---

packages/typescript-private/console/src/base/remote.ts
projects/console-web-server/src/db/entity/pipeline.entity.ts
projects/console-web-server/src/db/entity/remote.entity.ts
projects/console-web-server/src/db/migrations/local/1689761910941-typeorm-migration.ts
projects/console-web-server/src/module/remote/processor/remote-device-job-processor.ts
projects/console-web-server/src/module/remote/remote-dest/remote-dest.controller.ts
projects/console-web-server/src/module/remote/remote-dest/remote-dest.service.ts
projects/console-web-server/src/module/remote/remote-webdriver/remote-webdriver.service.ts
projects/console-web-server/src/module/remote/remote.module.ts

update: remote-report api

---

nm-space/projects/dost/electron/child/mains/device-server.ts
nm-space/projects/dost/electron/child/mains/host-agent.ts
nm-space/projects/dost/electron/main.ts
packages/typescript/node/src/environment-variables/replacement-providers.ts

fix: windows path environment variable issue

---

.vscode/tasks.json
packages/typescript-private/device-server/src/appium/appium.context.ts
packages/typescript-private/device-server/src/device-host/device-host.download-shared-resource.ts
packages/typescript-private/device-server/src/device-host/device-host.module.ts
packages/typescript-private/device-server/src/device-webdriver/appium.device-webdriver.handler.ts
packages/typescript-private/device-server/src/device-webdriver/device-webdriver.module.ts
packages/typescript-private/device-server/src/device-webdriver/endpoint-handler/appium.new-session.handler.ts
packages/typescript-private/device-server/src/device-webdriver/endpoint-handler/appium.service.ts
packages/typescript-private/device-server/src/device-webdriver/endpoint-handler/appium.session.handler.ts
packages/typescript-private/device-server/src/internal/util/net.ts
packages/typescript-private/device-server/src/ws/device-host/download-shared-resource.ts
packages/typescript-private/device-server/src/ws/ws.module.ts
packages/typescript/common/src/http-ws/constants.ts
packages/typescript/node/src/data-structure/task-queue.ts
projects/go-device-controller/internal/pkg/server/run.go

https://github.com/dogu-team/dogu/issues/197

fix: refactor: download host shared service

---

e2e/test/bat/bat-routine.test.ts
projects/console-web-front/pages/dashboard/[orgId]/devices/streaming/[deviceId].tsx
projects/console-web-front/src/components/streaming/DeviceStreamingLogContainer.tsx
projects/console-web-front/src/components/streaming/InspectorContextMenu.tsx
projects/console-web-front/src/components/streaming/StreamingVideo.tsx

ci: e2e for device streaming

---

e2e/src/chromedriver.ts
e2e/test/bat/bat-routine.test.ts
e2e/test/bat/bat/host.ts
projects/console-web-front/pages/account/index.tsx
projects/console-web-front/pages/dashboard/[orgId]/projects/[pid]/settings.tsx
projects/console-web-front/pages/dashboard/[orgId]/settings.tsx
projects/console-web-front/src/components/AccountMenu.tsx
projects/console-web-front/src/components/PermissionSelectContentBox.tsx
projects/console-web-front/src/components/common/AccessTokenButton.tsx
projects/console-web-front/src/components/common/RegenerateTokenButton.tsx
projects/console-web-front/src/components/common/boxes/DangerZone.tsx
projects/console-web-front/src/components/layouts/SideBarTitle.tsx
projects/console-web-front/src/components/layouts/TeamPageLayout.tsx
projects/console-web-front/src/components/project-application/ProjectApplicationUploadButton.tsx
projects/console-web-front/src/components/teams/AddProjectButton.tsx
projects/console-web-front/src/components/teams/AddProjectModal.tsx
projects/console-web-front/src/components/teams/TeamSettings.tsx

ci: e2e for org, project, team, account

---

projects/console-web-server/src/module/feature/file/implementations/nexus-feature-file.service.ts
projects/console-web-server/src/module/file/project-file.service.ts

fix: video-record issue

---

docker-compose.yml
projects/console-web-server/package.json
projects/console-web-server/scripts/common/common.ts
projects/console-web-server/scripts/start-influxdb/config.ts
projects/console-web-server/scripts/start-influxdb/run.ts
projects/console-web-server/scripts/start-nexus/config.ts
projects/console-web-server/scripts/start-nexus/run.ts
projects/console-web-server/scripts/start-pgsql/config.ts
projects/console-web-server/scripts/start-pgsql/run.ts
projects/console-web-server/scripts/start-turn-server/config.ts
projects/console-web-server/scripts/start-turn-server/run.ts
projects/console-web-server/scripts/typeorm/typeorm-init.ts

update: e2e-init script

---

packages/typescript-private/console/src/dto/feature/feature.dto.ts
packages/typescript-private/console/src/index.ts
packages/typescript/node/src/feature-config.ts
packages/typescript/types/src/organization/types.ts
projects/console-web-server/features/development.feature.config.json
projects/console-web-server/features/e2e.feature.config.json
projects/console-web-server/features/local.feature.config.json
projects/console-web-server/features/production.feature.config.json
projects/console-web-server/features/self-hosted.feature.config.json
projects/console-web-server/src/feature.config.ts
projects/console-web-server/src/module/app/app.module.ts
projects/console-web-server/src/module/auth/auth.module.ts
projects/console-web-server/src/module/auth/guard/email-verification.guard.ts
projects/console-web-server/src/module/feature/feature.controller.ts
projects/console-web-server/src/module/feature/feature.module.ts
projects/console-web-server/src/module/feature/feature.service.ts
projects/console-web-server/src/module/feature/file/feature-file.module.ts
projects/console-web-server/src/module/file/project-file.service.ts
projects/console-web-server/src/module/organization/organization.controller.ts
projects/console-web-server/src/sdk/s3.ts
projects/console-web-server/src/utils/cookie.ts

update: server feature api

---

.vscode/tasks.json
packages/typescript-private/device-server/src/appium/appium.context.ts
packages/typescript-private/device-server/src/appium/appium.service.ts
packages/typescript-private/device-server/src/device-webdriver/endpoint-handler/appium.new-session.handler.ts
packages/typescript-private/device-server/src/internal/driver/android-driver.ts
packages/typescript-private/device-server/src/internal/externals/cli/adb/adb.ts

fix: adb custom port to minimize interrupt

---

nm-space/projects/dost/electron/external/external-service.ts
nm-space/projects/dost/electron/external/external-unit.ts
nm-space/projects/dost/electron/external/units/ida-build-external-unit.ts
nm-space/projects/dost/electron/settings/ios-device-agent-project.ts
nm-space/projects/dost/src/components/external/ManualExternalToolValidCheckerItem.tsx
nm-space/projects/dost/src/components/layouts/HomeMenuSider.tsx
nm-space/projects/dost/src/hooks/manaul-setup-external-valid-result.ts
nm-space/projects/dost/src/pages/Doctor.tsx
nm-space/projects/dost/src/pages/iOSSettings.tsx
nm-space/projects/dost/src/shares/external.ts
nm-space/projects/dost/src/stores/ios-settings-status.ts
packages/typescript/node/src/filesystem.ts

Notify like below image,  if user local ios-device-agent project is outdated in DoguAgent

Notify if user local ios-device-agent project is outdated

---

packages/typescript-private/console/src/dto/record/record-test-scenario.dto.ts
projects/console-web-server/src/enterprise/module/record/common.ts
projects/console-web-server/src/enterprise/module/record/record-test-case/record-test-case.controller.ts
projects/console-web-server/src/enterprise/module/record/record-test-case/record-test-case.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-step/record-test-step.service.ts

wip:record-test

---

projects/console-web-front/i18n.json
projects/console-web-front/locales/en/routine.json
projects/console-web-front/locales/ko/routine.json
projects/console-web-front/pages/dashboard/[orgId]/projects/[pid]/routines/[pipelineId]/devices.tsx
projects/console-web-front/src/components/device/DeviceLiveCell.tsx
projects/console-web-front/src/components/pipelines/JobListController.tsx
projects/console-web-front/src/components/pipelines/PipelineDeviceGrid.tsx
projects/console-web-front/src/components/pipelines/PipelineListController.tsx
projects/console-web-front/src/components/streaming/DeviceStreaming.tsx
projects/console-web-front/src/components/streaming/StreamingVideo.tsx
projects/console-web-server/src/module/routine/pipeline/pipeline.service.ts
projects/console-web-server/src/ws/live-pipeline-status/live-pipeline-status.gateway.ts

feat: multi device view in routine

---

projects/console-web-front/pages/404.tsx

feat: custom 404 page with header

---

packages/typescript-private/console/src/base/record-test-action.ts
packages/typescript-private/console/src/base/record-test-step.ts
projects/console-web-server/src/enterprise/module/record/common.ts
projects/console-web-server/src/enterprise/module/record/record-test-action/record-test-action-webdriver-click.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-action/record-test-step-action.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-case/record-test-case.controller.ts
projects/console-web-server/src/enterprise/module/record/record-test-case/record-test-case.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-scenario/record-test-scenario.controller.ts
projects/console-web-server/src/enterprise/module/record/record-test-scenario/record-test-scenario.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-step/record-test-step.controller.ts
projects/console-web-server/src/enterprise/module/record/record-test-step/record-test-step.service.ts

wip: record-test-crud

---

packages/typescript-private/console/src/base/user.ts
projects/console-web-server/src/db/entity/user.entity.ts
projects/console-web-server/src/db/migrations/development/1692586246306-typeorm-migration.ts
projects/console-web-server/src/db/migrations/e2e/1692586246306-typeorm-migration.ts
projects/console-web-server/src/db/migrations/local/1692586246306-typeorm-migration.ts
projects/console-web-server/src/db/migrations/production/1692586246306-typeorm-migration.ts
projects/console-web-server/src/db/migrations/self-hosted/1692586246306-typeorm-migration.ts
projects/console-web-server/src/module/auth/auth.module.ts
projects/console-web-server/src/module/auth/guard/user-jwt.guard.ts

update: user-access-tracking

---

packages/typescript-private/console/src/base/record-test-action.ts
packages/typescript-private/console/src/base/record-test-step-action-webdriver-input.ts
packages/typescript-private/console/src/index.ts
packages/typescript-private/console/src/util/page-source/android.ts
packages/typescript-private/console/src/util/page-source/gamium.ts
packages/typescript-private/console/src/util/page-source/ios.ts
packages/typescript-private/console/src/util/page-source/types.ts
packages/typescript-private/types/src/index.ts
packages/typescript-private/types/src/record-test-step-action-webdrive-input/index.ts
packages/typescript-private/types/src/record-test-step-action-webdrive-input/types.ts
projects/console-web-server/src/db/entity/record-test-step-action-webdriver-input.entity.ts
projects/console-web-server/src/db/entity/record-test-step.entity.ts
projects/console-web-server/src/db/entity/type/type.ts
projects/console-web-server/src/db/migrations/development/1692674294301-typeorm-migration.ts
projects/console-web-server/src/db/migrations/e2e/1692674294301-typeorm-migration.ts
projects/console-web-server/src/db/migrations/local/1692674294301-typeorm-migration.ts
projects/console-web-server/src/db/migrations/production/1692674294301-typeorm-migration.ts
projects/console-web-server/src/db/migrations/self-hosted/1692674294301-typeorm-migration.ts
projects/console-web-server/src/enterprise/module/record/record-test-action/record-test-action-webdriver-click.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-action/record-test-action-webdriver-input.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-action/record-test-step-action.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-step/record-test-step.service.ts
projects/console-web-server/src/enterprise/module/record/record.module.ts

update: record-test-input-event

---

packages/typescript-private/console/src/base/record-test-case.ts
packages/typescript-private/console/src/base/record-test-scenario.ts
packages/typescript-private/console/src/base/record-test-step.ts
projects/console-web-server/src/db/entity/record-test-case.entity.ts
projects/console-web-server/src/db/entity/record-test-step.entity.ts
projects/console-web-server/src/db/migrations/development/1693200893980-typeorm-migration.ts
projects/console-web-server/src/db/migrations/e2e/1693200893980-typeorm-migration.ts
projects/console-web-server/src/db/migrations/local/1693200893980-typeorm-migration.ts
projects/console-web-server/src/db/migrations/production/1693200893980-typeorm-migration.ts
projects/console-web-server/src/db/migrations/self-hosted/1693200893980-typeorm-migration.ts
projects/console-web-server/src/enterprise/module/record/common.ts
projects/console-web-server/src/enterprise/module/record/record-test-action/record-test-step-action.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-case/record-test-case.service.ts
projects/console-web-server/src/enterprise/module/record/record-test-step/record-test-step.service.ts

refactor: record-test db

---

packages/typescript-private/console/src/dto/record/record-test-scenario.dto.ts
projects/console-web-server/src/enterprise/module/record/common.ts
projects/console-web-server/src/enterprise/module/record/dto/record-test-scenario.dto.ts
projects/console-web-server/src/enterprise/module/record/record-test-scenario/record-test-scenario.controller.ts
projects/console-web-server/src/enterprise/module/record/record-test-scenario/record-test-scenario.service.ts

update: record-test-scenario crud

---

packages/typescript-private/console/src/base/project.ts
packages/typescript-private/console/src/dto/project/project.dto.ts
packages/typescript/types/src/project/types.ts
projects/console-web-front/locales/en/organization.json
projects/console-web-front/locales/en/project.json
projects/console-web-front/locales/ko/organization.json
projects/console-web-front/locales/ko/project.json
projects/console-web-front/pages/dashboard/[orgId]/projects/[pid]/settings.tsx
projects/console-web-front/src/components/projects/CreateProjectModal.tsx
projects/console-web-front/src/components/projects/ProjectTypeRadio.tsx
projects/console-web-front/src/components/projects/UpdateTemplateButton.tsx
projects/console-web-server/src/db/entity/project.entity.ts
projects/console-web-server/src/db/migrations/development/1693221304423-typeorm-migration.ts
projects/console-web-server/src/db/migrations/e2e/1693221304423-typeorm-migration.ts
projects/console-web-server/src/db/migrations/local/1693221304423-typeorm-migration.ts
projects/console-web-server/src/db/migrations/production/1693221304423-typeorm-migration.ts
projects/console-web-server/src/db/migrations/self-hosted/1693221304423-typeorm-migration.ts
projects/console-web-server/src/module/organization/organization.service.ts
projects/console-web-server/src/module/project/dto/project.dto.ts
projects/console-web-server/src/module/project/project.service.ts

feat: project type on creation and updating

---

dogu-actions/run-test/src/main.ts
packages/typescript-private/host-agent/src/message/message.request-response-controller.ts
packages/typescript-private/host-agent/src/processor/command.process-registry.ts

fix: multiline command #383

---

nm-space/projects/dost/electron/child/instances/device-server.ts
nm-space/projects/dost/electron/preload.ts
nm-space/projects/dost/electron/settings/settings-service.ts
nm-space/projects/dost/src/components/external/ManualExternalToolDetail.tsx
nm-space/projects/dost/src/components/external/ManualExternalToolValidCheckerItem.tsx
nm-space/projects/dost/src/components/external/XCodeProjectBuildDescription.tsx
nm-space/projects/dost/src/components/overlays/RestartAlert.tsx
nm-space/projects/dost/src/pages/MacOSSettings.tsx
nm-space/projects/dost/src/pages/iOSSettings.tsx
nm-space/projects/dost/src/shares/app-config.ts
nm-space/projects/dost/src/shares/settings.ts
packages/python/dogu-device-client/dogu/device/__init__.py
packages/typescript-private/device-server/src/internal/channel/ios-channel.ts
packages/typescript-private/device-server/src/internal/externals/cli/ios-device-agent.ts
packages/typescript-private/device-server/src/internal/externals/cli/webdriver-agent-process.ts
packages/typescript-private/device-server/src/internal/externals/cli/xcodebuild.ts
packages/typescript-private/device-server/src/internal/externals/cli/xctrace.ts
packages/typescript-private/dost-children/src/envs/device-server.ts
packages/typescript-private/host-agent/src/processor/routine.workspace.ts
packages/typescript/common/src/date.ts
projects/go-device-controller/internal/pkg/device/surface/aos_surface.go
projects/go-device-controller/internal/pkg/device/surface/desktop_libwebrtc_surface.go
projects/go-device-controller/internal/pkg/device/surface/ios_surface.go
projects/go-device-controller/internal/pkg/device/surface/surface.go
projects/go-device-controller/internal/pkg/utils/size_prefixed_recv_queue.go

- fix: routine workspace find error
- fix: gdc surface reconnect spin
- feat: restart ios device when starting connection
https://github.com/dogu-team/dogu/assets/22186124/7df9a478-c48b-4503-9591-50e2cb917ece

Restart iOS device when starting connection option

---

packages/typescript-private/host-agent/src/processor/action.processor.ts
packages/typescript/action-kit/src/built-in-actions/checkout-project.ts

fix: git checkout failure #390

---

packages/typescript-private/host-agent/src/host/host.resolver.ts
packages/typescript/node/src/logs.ts

fix: remove old logs  #364

---

nm-space/projects/dost/electron/external/units/appium-uiautomator2-driver-external-unit.ts
nm-space/projects/dost/src/components/external/ExternalToolInstallerModal.tsx
nm-space/projects/dost/src/pages/iOSSettings.tsx

feat: turn off chromedriver intallation

---

e2e/test/bat/bat-routine.test.ts
packages/typescript-private/console/src/base/project-application.ts
packages/typescript-private/console/src/dto/project-application/project-application.dto.ts
projects/console-web-front/locales/en/common.json
projects/console-web-front/locales/en/project-app.json
projects/console-web-front/locales/ko/common.json
projects/console-web-front/locales/ko/project-app.json
projects/console-web-front/src/api/project-application.ts
projects/console-web-front/src/components/project-application/ProjectApplicationListController.tsx
projects/console-web-front/src/components/project-application/ProjectApplicationUploadButton.tsx
projects/console-web-server/src/db/entity/project-application.entity.ts
projects/console-web-server/src/db/migrations/development/1694498462209-typeorm-migration.ts
projects/console-web-server/src/db/migrations/e2e/1694498462209-typeorm-migration.ts
projects/console-web-server/src/db/migrations/local/1694498462209-typeorm-migration.ts
projects/console-web-server/src/db/migrations/production/1694498462209-typeorm-migration.ts
projects/console-web-server/src/db/migrations/self-hosted/1694498462209-typeorm-migration.ts
projects/console-web-server/src/module/open-api/v1/project/project.controller.ts
projects/console-web-server/src/module/open-api/v1/project/project.service.ts
projects/console-web-server/src/module/project/application/application.controller.ts
projects/console-web-server/src/module/project/application/application.service.ts
projects/console-web-server/src/module/project/application/dto/application.dto.ts

feat: upload app with `latest` option

---

packages/typescript/action-kit/src/built-in-actions/checkout-project.ts

fix: apply changed git url  #403

---

projects/console-web-server/src/db/entity/device.entity.ts
projects/console-web-server/src/module/private/private-device.controller.ts

feat: default host device job count #434

---

projects/console-web-server/src/module/routine/pipeline/pipeline.service.ts

fix: over-device-runner-count  #442

---

packages/typescript-private/console/src/base/user-email-preference.ts
projects/console-web-front/pages/services/newsletter/unsubscribe.tsx
projects/console-web-server/src/db/entity/user-email-preference.entity.ts
projects/console-web-server/src/db/migrations/development/1694593550551-typeorm-migration.ts
projects/console-web-server/src/db/migrations/e2e/1694593550551-typeorm-migration.ts
projects/console-web-server/src/db/migrations/local/1694593550551-typeorm-migration.ts
projects/console-web-server/src/db/migrations/production/1694593550551-typeorm-migration.ts
projects/console-web-server/src/db/migrations/self-hosted/1694593550551-typeorm-migration.ts
projects/console-web-server/src/module/registery/common.ts
projects/console-web-server/src/module/registery/registery.controller.ts
projects/console-web-server/src/module/registery/registery.service.ts
projects/console-web-server/src/module/token/token.service.ts

feat: email subscription on public

---

dogu-actions/checkout/action.config.yaml
dogu-actions/checkout/src/main.ts
dogu-actions/prepare/action.config.yaml
dogu-actions/prepare/src/main.ts
dogu-actions/run-test/action.config.yaml
dogu-actions/run-test/src/main.ts
packages/typescript-private/host-agent/src/processor/action.processor.ts
packages/typescript/action-kit/src/built-in-actions/checkout-project.ts
packages/typescript/node/src/git.ts

fix: git checkout with branch or tag #394

---

projects/console-web-front/src/components/routine/editor/RoutineCreator.tsx

fix: routine web example

---

packages/typescript-private/device-server/src/internal/externals/cli/mobiledevice-tunnel.ts
packages/typescript-private/types/src/platforms.ts
packages/typescript/device-client-common/src/validations/types/device-configs.ts
packages/typescript/node/src/processes.ts

- [x Local, Self Hosted and Development environment test finished.

wip: add missing codes on linux

---

projects/console-web-front/locales/en/routine.json
projects/console-web-front/locales/ko/routine.json
projects/console-web-front/pages/api/browsers/[browser]/available-versions.ts
projects/console-web-front/pages/dashboard/[orgId]/get-started/index.tsx
projects/console-web-front/src/components/routine/editor/gui/BrowserPicker.tsx
projects/console-web-front/src/components/routine/editor/gui/BrowserStatusTag.tsx
projects/console-web-front/src/components/routine/editor/gui/JobContainer.tsx
projects/console-web-front/src/components/tutorial/CloudUserTutorial.tsx

feat: browser picker in routine

---

projects/console-web-front/src/components/layouts/ConsoleBasicLayout.tsx
projects/console-web-front/src/components/layouts/ConsoleLayout.tsx
projects/console-web-front/src/components/layouts/OrganizationSideBar.tsx
projects/console-web-front/src/components/layouts/ProjectLayoutWithSidebar.tsx
projects/console-web-front/src/components/layouts/ProjectSideBar.tsx

fix: layout with fixed sidebar

---

packages/typescript-private/device-server/src/internal/driver/linux-driver.ts
packages/typescript-private/dogu-agent-core/src/app/child/device-server/child.ts
packages/typescript-private/dogu-agent-core/src/shares/app-config.ts
packages/typescript-private/dost-children/src/envs/device-server.ts
projects/dogu-agent/src/cli.ts
projects/dogu-agent/src/commands/run.ts
shells/entrypoint-dogu-agent.sh

feat: linux device serial #491

---

packages/typescript-private/console/src/base/cloud-device.ts
packages/typescript-private/console/src/dto/cloud-device/cloud-device.dto.ts
packages/typescript-private/console/src/index.ts
projects/console-web-front/enterprise/components/studio/RecordTesting.tsx
projects/console-web-front/enterprise/components/studio/StudioLayout.tsx
projects/console-web-front/enterprise/pages/studio.tsx
projects/console-web-front/i18n.json
projects/console-web-front/locales/en/organization.json
projects/console-web-front/locales/ko/organization.json
projects/console-web-front/pages/dashboard/[orgId]/live-testing/[deviceId].tsx
projects/console-web-front/pages/dashboard/[orgId]/live-testing/index.tsx
projects/console-web-front/pages/dashboard/[orgId]/projects/[pid]/studio/[deviceId]/manual.tsx
projects/console-web-front/src/api/cloud-device.ts
projects/console-web-front/src/api/device.ts
projects/console-web-front/src/components/cloud/CloudDeviceSelectList.tsx
projects/console-web-front/src/components/cloud/LiveTestingCloudDeviceList.tsx
projects/console-web-front/src/components/layouts/OrganizationSideBar.tsx
projects/console-web-front/src/components/studio/DeviceStreamingLayout.tsx
projects/console-web-front/src/components/studio/ManualTesting.tsx
projects/console-web-front/src/resources/device/brand.ts
projects/console-web-server/src/module/cloud-device/cloud-device.controller.ts
projects/console-web-server/src/module/cloud-device/cloud-device.dto.ts
projects/console-web-server/src/module/cloud-device/cloud-device.module.ts
projects/console-web-server/src/module/cloud-device/cloud-device.service.ts

feat: cloud device list ui
